<?php
namespace backend\widgets;

use backend\models\Menu;
use yii\bootstrap\Widget;
use yii\bootstrap\NavBar;
use Yii;
use yii\bootstrap\Html;
use yii\bootstrap\Nav;

class MenuWidget extends Widget{
    //widget被实例化后执行的代码
    public function init()
    {
        parent::init();
    }
    public function run()
    {
        NavBar::begin([
            'brandLabel' => '京西商城',
            'brandUrl' => Yii::$app->homeUrl,
            'options' => [
                'class' => 'navbar-inverse navbar-fixed-top',
            ],
        ]);
//        $menuItems = [
//            ['label' => '品牌管理', 'url' => ['/brand/index']],
//            ['label' => '文章分类', 'url' => ['/article-category/index']],
//            ['label' => '文章管理', 'url' => ['/article/index']],
//            ['label' => '商品分类', 'url' => ['/goods-category/index']],
//            ['label' => '商品管理', 'url' => ['/goods/index']],
//            ['label' => '管理员', 'url' => ['/admin-user/index']],
//            ['label' => '权限管理', 'items'=>[
//                ['label' => '权限管理', 'url' => ['/rbac/permission-index']],
//                ['label' => '角色管理', 'url' => ['/rbac/role-index']]
//            ]
//            ],
//        ];
        if (Yii::$app->user->isGuest) {
            $menuItems[] = ['label' => '登陆', 'url' => ['/admin/login']];
        } else {
            $menuItems=[];
            //获取一级菜单
            $menus=Menu::findAll(['parent_id'=>0]);
            //获取所有一级菜单
            $menus = Menu::findAll(['parent_id'=>0]);
            foreach ($menus as $menu){
                $item = ['label'=>$menu->label,'items'=>[]];
                foreach ($menu->children as $child){
                    //根据用户权限判断，该菜单是否显示
                    if(Yii::$app->user->can($child->url)){
                        $item['items'][] = ['label'=>$child->label,'url'=>[$child->url]];
                    }

                }
                //如果该一级菜单没有子菜单，就不显示
                if(!empty($item['items'])){
                    $menuItems[] = $item;
                }

            }
            $menuItems[] = '<li>'
                . Html::beginForm(['/admin/logout'], 'post')
                . Html::submitButton(
                    '注销 (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>';
        }
        echo Nav::widget([
            'options' => ['class' => 'navbar-nav navbar-right'],
            'items' => $menuItems,
        ]);
        NavBar::end();
        parent::run(); // TODO: Change the autogenerated stub
    }

}